name: CI Portfolio Astro

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Verificar Build de Astro
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Instalar dependencias
        run: npm ci

      - name: Construir el proyecto (Build)
        run: npm run build